

SELECT RESTAURANTE.nome
FROM RESTAURANTE
WHERE RESTAURANTE.nomeCategRestaurante = 'Churrascaria';

SELECT CLIENTE.endereco
FROM CLIENTE,PEDIDO
WHERE CLIENTE.idCliente = PEDIDO.idCliente AND PEDIDO.idPedido = 0;


SELECT PRODUTO.nome
FROM PRODUTO
WHERE PRODUTO.nomeCategoria = 'Sobremesa';

SELECT RESTAURANTE.CNPJ
FROM RESTAURANTE
WHERE RESTAURANTE.nome = 'Vacaria';


SELECT CLIENTE.telefone
FROM CLIENTE
WHERE CLIENTE.nome = 'Daniel';

SELECT CARTAO.numeracao, CARTAO.nomeTitular, CARTAO.validade, CARTAO.cvv
FROM CARTAO
WHERE CARTAO.nome = 'Débito';

SELECT AUTOMOVEL.cor, AUTOMOVEL.tipo, AUTOMOVEL.modelo
FROM AUTOMOVEL
WHERE AUTOMOVEL.idAutomovel = 0;

SELECT ENTREGADOR.nome
FROM ENTREGADOR,PEDIDO
WHERE ENTREGADOR.identregador = PEDIDO.identregador AND PEDIDO.idPedido = 0;

SELECT AVALIACAO.idPedido
FROM AVALIACAO
WHERE AVALIACAO.nota >= 4;

SELECT AVALIACAO.nota, AVALIACAO.comentario
FROM AVALIACAO,restaurante
WHERE RESTAURANTE.idRestaurante = AVALIACAO.idRestaurante AND RESTAURANTE.nome = 'Vacaria';